In [1]:
#array processing package
l=[[1,1],[2,2],[3,5],[4,5]]
l

[[1, 1], [2, 2], [3, 5], [4, 5]]

In [4]:
k=[[6,9],[8,9],[4,5],[7,9]]
k

[[6, 9], [8, 9], [4, 5], [7, 9]]

In [5]:
import numpy as np

In [6]:
np_arr=np.array(k)
np_arr

array([[6, 9],
       [8, 9],
       [4, 5],
       [7, 9]])

In [7]:
type(k),type(np_arr) #nd=n dimensional

(list, numpy.ndarray)

In [8]:
ls1=[1,2,3,4]
ls2=[2,3,5,6]
ls3=[5,7,3,2]

merged=np.array([ls1,ls2,ls3])
merged

array([[1, 2, 3, 4],
       [2, 3, 5, 6],
       [5, 7, 3, 2]])

In [9]:
merged.shape

(3, 4)

In [10]:
merged[0]

array([1, 2, 3, 4])

In [11]:
merged[0][0]

1

In [12]:
merged[1][2]

5

In [13]:
merged[1:]

array([[2, 3, 5, 6],
       [5, 7, 3, 2]])

In [14]:
merged[1:,2:]

array([[5, 6],
       [3, 2]])

In [15]:
merged[0:2,2:]

array([[3, 4],
       [5, 6]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.ones((2,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.random.rand(2,2)

array([[0.46696251, 0.15428968],
       [0.31532802, 0.89047958]])

In [22]:
np.random.rand(3,3)

array([[0.29153419, 0.99603659, 0.04928513],
       [0.45662819, 0.01128576, 0.06528163],
       [0.10942481, 0.86266723, 0.77455207]])

In [23]:
n=np.arange(10,20)
n.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
np.random.randint(2)

0